### ISSUE TITLE
Profibus Module configuration tag list box allows duplicate assignment of tags.

### ISSUE THREAD

**Issue by leesecho** [TBDFramework/ProfibusModules#13]
Configuring a channel to use a tag does not remove it from the list of available tags for other channels.

**Comment by dsmithni** [comment]
Is the channel a reader channel?

**Comment by leesecho** [comment]
Yes, the direction for these channels is "Write to HW." Ok, so I am assuming that this is intended behavior. Correct?

**Comment by leesecho** [comment]
Per our conversation, multiple readers is allowed and so this was not an issue.
