### ISSUE TITLE
Tags in the Mappings view are not removed after they are assigned.

### ISSUE THREAD

**Issue by leesecho** [TBDFramework/ProfibusModules#14]
Until all Profibus channels for a given data type are assigned, all tags remain available in the "Tags" list box. This creates the possibility of duplicate assignment of tags.

**Comment by dsmithni** [comment]
Why is this different from #13?

**Comment by leesecho** [comment]
It is a different view, although I agree that the root cause may be the same.

**Comment by dsmithni** [comment]
@leesecho can you confirm if we decided this was correct behavior?
