### ISSUE TITLE
"Linked Tag" listbox does not populate with tags of every data type.

### ISSUE THREAD

**Issue by leesecho** [TBDFramework/ProfibusModules#9]
Boolean tags appear, but tags of single data type do not.

**Comment by dsmithni** [comment]
can you segment this into smaller issues please? Sounds like they are "add sorting to type field", "make data type field name consistent across modules", and...whatever you mean baout boolean vs single tags? Are you sure you had a single channel selected? Tags are filtered by type.

**Comment by leesecho** [comment]
Per our conversation, Scan Engine supports DBL data type only.
